apiVersion: v1
kind: Namespace
metadata:
  name: product-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: product-manager
type: Opaque
stringData:
  SA_PASSWORD: 'YourStrong@Passw0rd'
